menu:
  主页(Home): /
  归档(Archives): /archives
  我收藏的站: /daohang
  关于(About): /about

widgets:
- search
- category
- aboutme
- tagcloud
- weibo


excerpt_link: 阅读全文

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

baidu_tongji: true
google_analytics: true
rss:

comment_provider: facebook
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light